<?php
/**
 * Default configuration values.
 *
 * @copyright 2015-2016 Austin S.
 * @license http://www.opensource.org/licenses/gpl-2.0.php GNU GPL v2
 */

// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/*.php files.

$Configuration['Articles']['ShowArticlesMenuLink'] = true;
$Configuration['Articles']['ShowCategoriesMenuLink'] = false;
$Configuration['Articles']['Excerpt']['MaxLength'] = 160;
$Configuration['Articles']['Articles']['ThumbnailWidth'] = 280;
$Configuration['Articles']['Articles']['ThumbnailHeight'] = 200;
$Configuration['Articles']['Articles']['AddActivity'] = false;
$Configuration['Articles']['Articles']['ShowAuthorInfo'] = false;
$Configuration['Articles']['Articles']['ShowSimilarArticles'] = true;
$Configuration['Articles']['Comments']['EnableThreadedComments'] = true;
$Configuration['Articles']['Comments']['AllowGuests'] = false;
$Configuration['Articles']['Comments']['AddActivity'] = false;
$Configuration['Articles']['Modules']['ShowCategoriesAsDropDown'] = false;
