<?php if (!defined('APPLICATION')) exit();
/**
 * Copyright (C) 2015  Austin S. (Shadowdare)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/*.php files.

$Configuration['Articles']['ShowMenuLink'] = true;
$Configuration['Articles']['Excerpt']['MaxLength'] = 160;
$Configuration['Articles']['Articles']['ThumbnailWidth'] = 260;
$Configuration['Articles']['Articles']['ThumbnailHeight'] = 146;
$Configuration['Articles']['Articles']['AddActivity'] = true;
$Configuration['Articles']['Comments']['EnableThreadedComments'] = true;
$Configuration['Articles']['Comments']['AllowGuests'] = false;
$Configuration['Articles']['Comments']['AddActivity'] = true;
